### ISSUE TITLE
16 pin ILI9488 3.5inch 320x480 with STM32F411CE won't work for me.

### ISSUE THREAD

**Issue by douginarug** [nopnop2002/Arduino-STM32-8bitTFT#6]
I've got an Open-Smart 16 pin ILI9488 3.5inch 320x480  "expansion module" from e-bay.  
https://www.ebay.com/itm/3-5inch-TFT-Board-Expansion-Module-LCD-Touch-Screen-For-R3-Nano-Mega2560-Hot/233641518844?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649
I hooked it up to a Black Pill STM32F411CE.  
I looked at the .cpp and saw it briefly mentioned the ILI9488 but I'm not sure if it supports it.  (I don't really understand the code.) I'm probably doing something wrong.
I ran the GraphicsTest_320x480_SMT32.ino and it looks like it is communicating with each other but there is nothing on the tft screen.  In the Serial Monitor I am seeing this;

Arduino-STM32-8bitTFT
readReg16(0)=0x0
readReg32(A1)=0x3093
readReg40(BF)=0x9393
readReg32(D4)=0x0
readReg40(EF)=0x0
readReg32(FE)=0x0
readReg32(04)=0x548066
readReg32(D3)=0x9488
Device ID: 0x9488
Width: 320
Height: 480
Benchmark                Time (microseconds)
Screen fill              2115372
Text                     77333
Lines                    962493
Horiz/Vert Lines         182033
Rectangles (outline)     108761
Rectangles (filled)      5310698
Circles (filled)         1258549
Circles (outline)        411223
Triangles (outline)      194504
Triangles (filled)       1925425
Rounded rects (outline)  197330
Rounded rects (filled)   5885654
Done!

![20210127_100740](https://user-images.githubusercontent.com/7226258/106013071-1ccecb80-608a-11eb-8683-3ab28c4c96c4.jpg)
![20210127_100749](https://user-images.githubusercontent.com/7226258/106013086-1f312580-608a-11eb-9fb6-f140769f6449.jpg)
![20210127_100914](https://user-images.githubusercontent.com/7226258/106013095-20fae900-608a-11eb-8809-719e0cef8b6c.jpg)
![20210127_101018](https://user-images.githubusercontent.com/7226258/106013101-235d4300-608a-11eb-980b-edcff4d3318f.jpg)

Thank you in advance for any help you could give me.
Doug

**Comment by nopnop2002** [comment]
I'll order Open-Smart 16 pin ILI9488 3.5inch 320x480.


It will arrive at me at the end of February.

**Comment by douginarug** [comment]
Wow, that would be great. It is very nice of you to do that. I really  appreciate you taking the time to help.
Doug



Sent from my phone.



-------- Original message --------

**Comment by douginarug** [comment]
Since prenticedavid/MCUFRIEND_kbv library says it only works with 28 pin shields, I did some looking for a library for the 16 pin board.  I found this on YouTube from Frankie Chu.
https://www.youtube.com/watch?v=BW84pk771bU 
He has a link to a google drive with an Arduino library for the ILI9488 16 pin board. 
https://drive.google.com/drive/folders/1RD0MlwHU44_1awyqCGptSnMxpQIjxt85
I wired up an Arduino Pro Mini 8Mhz 3.3V and got the graphicstest.ino to work with that library.
I just wish I knew how to port it for a STM32F411CE.  Ha ha.  That is way beyond me right now. Maybe it will help you though.
Thanks,
Doug

![20210203_100104 pro mini working](https://user-images.githubusercontent.com/7226258/106772584-29b16900-660e-11eb-8816-cd870219c508.jpg)

**Comment by nopnop2002** [comment]
Perhaps OPEN-SMART products cannot follow high-speed GPIO-ON and GPIO-OFF.

I think it is necessary to operate with low speed GPIO-ON and GPIO-OFF.

prenticedavid/MCUFRIEND_kbv library use high-speed GPIO ON /OFF.

Perhaps Arduino library for the ILI9488 16 pin board use low speed GPIO ON /OFF.

**Comment by douginarug** [comment]
I am just curious. What touchscreen library do you use with the Arduino-STM32-8bitTFT?

**Comment by nopnop2002** [comment]
I have never used a touch screen library.

Perhaps for this module you can read the touchscreen position with RD = Low & WR = High.
Position data is read from CX & CY.

But I haven't tried it.

**Comment by douginarug** [comment]
Did you ever receive your order for Open-Smart 16 pin ILI9488 3.5inch 320x480 display?

**Comment by nopnop2002** [comment]
I got these Open-Smart 16-pin display.

```
OPEN-SMART S6D1121 16Pin-Parallel
OPEN-SMART ST7775 16Pin-Parallel
OPEN-SMART ST7783 16Pin-Parallel
OPEN-SMART R61509V 16Pin-Parallel
OPEN-SMART ILI9488 16Pin-Parallel
```

I found that these display cannot follow high-speed GPIO-ON and GPIO-OFF.
It's hardware side issues.
The Arduino Pro Mini 8Mhz 3.3V is slow so they work.

These Open-Smart Shields work fine with high speed.

```
OPEN-SMART ILI9225 TFT-Shield
OPEN-SMART ILI9327 TFT-Shield
OPEN-SMART ILI9340 TFT-Shield
```
