### ISSUE TITLE
direct write registor will be more faster

### ISSUE THREAD

**Issue by liyang5945** [nopnop2002/Arduino-STM32-8bitTFT#9]
connet lcd data pin to a GPIO pot 0~7pin，then change the function `STM32_TFT_8bit::write8` to:
```
void STM32_TFT_8bit::write8(uint8_t bytes) {
    TFT_DATA->ODR = bytes;
}
```
write speed will more fast, here is my benchmark result,  left is after change, my board is F411CEU6

![2023_06_21_21_39_05](https://github.com/nopnop2002/Arduino-STM32-8bitTFT/assets/23631026/450e92ec-e8ba-45ed-9264-377bb9d8abf5)

![2023_06_21_21_42_13](https://github.com/nopnop2002/Arduino-STM32-8bitTFT/assets/23631026/d4e5928e-19db-49b3-8ef1-850ab47e8378)

**Comment by nopnop2002** [comment]
```
void STM32_TFT_8bit::write8(uint8_t bytes) {
    TFT_DATA->ODR = bytes;
}
````

Is this code valid for all STM32?

My code should work on STM32F0/F1/F2/F3/F4/F7/G0/G4/H5/H7/L0/L1/L4/L5/U5/WB/WL.

**Comment by liyang5945** [comment]
I search the CMSIS header files, every STM32 MCU  both have GPIO  ODR registor, so it works for all.
use this method, the  lcd data pin have to connent  to a GPIO port 0-7pin and rest of the GPIO pin 8-15 can't be used

![2023_06_22_00_16_19](https://github.com/nopnop2002/Arduino-STM32-8bitTFT/assets/23631026/0d74dc6d-e910-4c8c-bd93-29bba56dea22)

![2023_06_22_00_16_39](https://github.com/nopnop2002/Arduino-STM32-8bitTFT/assets/23631026/6f4dcdc1-7bf1-487c-8a32-6dda89bb28f3)

**Comment by nopnop2002** [comment]
>I search the CMSIS header files, every STM32 MCU both have GPIO ODR registor, so it works for all.

Thank you for your research.

>use this method, the lcd data pin have to connent to a GPIO port 0-7pin and rest of the GPIO pin 8-15 can't be used

I understand

Your proposal is very attractive.

I will consider whether to accept your proposal over the weekend.

**Comment by nopnop2002** [comment]
Changed from LL_GPIO_WriteOutputPort function to port output data (ODR) register.

You can toggle the behavior with this definition.

https://github.com/nopnop2002/Arduino-STM32-8bitTFT/blob/master/Arduino-STM32-8bitTFT.h#L59


thank you.
